#!/usr/bin/env node

import CleanCSS from "clean-css";
import { minify as minifyHTML } from "html-minifier-terser";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { FontAssetType, OtherAssetType, generateFonts } from "@twbs/fantasticon";

await mkdir("./fonts", { recursive: true });
await generateFonts({
    inputDir: "./node_modules/@primer/octicons/build/svg",
    outputDir: ".",
    name: "octicons",
    fontTypes: [
        FontAssetType.EOT,
        FontAssetType.WOFF2,
        FontAssetType.WOFF,
    ],
    assetTypes: [
        OtherAssetType.CSS,
        OtherAssetType.HTML,
    ],
    pathOptions: {
        woff: "./fonts/octicons.woff",
        woff2: "./fonts/octicons.woff2",
        eot: "./fonts/octicons.eot",
    },
    fontHeight: 300,
    descent: undefined,
    normalize: true,
    round: undefined,
    selector: null,
    tag: "i",
    templates: {
        css: "./octicons.css.hbs",
        html: "./octicons.html.hbs"
    },
    fontsUrl: "./fonts",
    prefix: "octicon",
});

const { styles } = await new CleanCSS({ returnPromise: true }).minify(["./octicons.css"]);
await writeFile("./octicons.min.css", styles, { flag: "w+" });
const html = await readFile("./octicons.html", "utf-8")
const preview = await minifyHTML(html, {
    collapseWhitespace: true,
    minifyCSS: true,
    minifyJS: true,
    removeComments: true,
})
await writeFile("./octicons.html", preview, { flag: "w+" })
