name: 'Generate CSS files and publish to NPM'
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm clean-install
      - name: Generate CSS files
        run: npm run generate
      - name: Prepare files
        run: |
          mkdir octicons
          cp -r fonts octicons.css octicons.min.css README.md LICENSE octicons/
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: octicons-css
          path: octicons/
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Prepare release
        run: tar -zcvf octicons.tar.gz octicons
      - name: Create release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: octicons.tar.gz
      - name: Clean up generated files
        run: npm run clean
